"""Add loans table

Revision ID: 633cb093557c
Revises: 2c8fd7c5b2da
Create Date: 2026-06-27 19:39:11.957131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add loans table

Revision ID: 633cb093557c
Revises: 2c8fd7c5b2da
Create Date: 2026-06-27 19:39:11.957131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633cb093557c'
down_revision: Union[str, None] = '2c8fd7c5b2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('autopay_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed')", name='ck_loans_status_valid'),
    sa.CheckConstraint('due_day >= 1 AND due_day <= 31', name='ck_loans_due_day_range'),
    sa.CheckConstraint('emi_amount >= 0', name='ck_loans_emi_amount_non_negative'),
    sa.CheckConstraint('interest_rate >= 0', name='ck_loans_interest_rate_non_negative'),
    sa.CheckConstraint('principal_amount > 0', name='ck_loans_principal_positive'),
    sa.CheckConstraint('tenure_months > 0', name='ck_loans_tenure_months_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('loan_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'loans', ['loan_id'], ['id'])
    
    # Custom: Drop and recreate single source link constraint
    op.drop_constraint('ck_transactions_single_source_link', 'transactions', type_='check')
    op.create_check_constraint(
        'ck_transactions_single_source_link',
        'transactions',
        '(CASE WHEN bill_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN subscription_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN loan_id IS NOT NULL THEN 1 ELSE 0 END) <= 1'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom: Drop and restore previous single source link constraint
    op.drop_constraint('ck_transactions_single_source_link', 'transactions', type_='check')
    op.create_check_constraint(
        'ck_transactions_single_source_link',
        'transactions',
        'bill_id IS NULL OR subscription_id IS NULL'
    )
    
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'loan_id')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
