"""add_interest_type_columns

Revision ID: f28d9d1ad4e3
Revises: fe9233e257d5
Create Date: 2026-06-28 19:17:17.968401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_interest_type_columns

Revision ID: f28d9d1ad4e3
Revises: fe9233e257d5
Create Date: 2026-06-28 19:17:17.968401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28d9d1ad4e3'
down_revision: Union[str, None] = 'fe9233e257d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts_lent', sa.Column('interest_type', sa.String(), nullable=False, server_default='simple'))
    op.add_column('loans', sa.Column('interest_type', sa.String(), nullable=False, server_default='compound'))
    
    op.create_check_constraint(
        'ck_debts_lent_interest_type_valid',
        'debts_lent',
        "interest_type IN ('simple', 'compound')"
    )
    op.create_check_constraint(
        'ck_loans_interest_type_valid',
        'loans',
        "interest_type IN ('simple', 'compound')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_loans_interest_type_valid', 'loans', type_='check')
    op.drop_constraint('ck_debts_lent_interest_type_valid', 'debts_lent', type_='check')
    op.drop_column('loans', 'interest_type')
    op.drop_column('debts_lent', 'interest_type')
    # ### end Alembic commands ###
