"""add_debts_lent_table

Revision ID: fe9233e257d5
Revises: 633cb093557c
Create Date: 2026-06-27 22:23:27.544042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9233e257d5'
down_revision: Union[str, None] = '633cb093557c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts_lent',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('borrower_name', sa.String(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate_type', sa.String(), nullable=False),
    sa.Column('interest_rate_val', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_rate_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('interest_frequency', sa.String(), nullable=False),
    sa.Column('lent_at', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("interest_frequency IN ('monthly', 'yearly')", name='ck_debts_lent_frequency_valid'),
    sa.CheckConstraint("interest_rate_type IN ('percentage', 'rupees_per_amount')", name='ck_debts_lent_rate_type_valid'),
    sa.CheckConstraint("status IN ('active', 'settled')", name='ck_debts_lent_status_valid'),
    sa.CheckConstraint('interest_rate_val >= 0', name='ck_debts_lent_interest_rate_val_non_negative'),
    sa.CheckConstraint('principal_amount > 0', name='ck_debts_lent_principal_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_lent_user_id'), 'debts_lent', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('lent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'debts_lent', ['lent_id'], ['id'])
    
    # Custom: Drop and recreate single source link constraint
    op.drop_constraint('ck_transactions_single_source_link', 'transactions', type_='check')
    op.create_check_constraint(
        'ck_transactions_single_source_link',
        'transactions',
        '(CASE WHEN bill_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN subscription_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN loan_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN lent_id IS NOT NULL THEN 1 ELSE 0 END) <= 1'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom: Drop and restore previous single source link constraint
    op.drop_constraint('ck_transactions_single_source_link', 'transactions', type_='check')
    op.create_check_constraint(
        'ck_transactions_single_source_link',
        'transactions',
        '(CASE WHEN bill_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN subscription_id IS NOT NULL THEN 1 ELSE 0 END + '
        'CASE WHEN loan_id IS NOT NULL THEN 1 ELSE 0 END) <= 1'
    )

    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'lent_id')
    op.drop_index(op.f('ix_debts_lent_user_id'), table_name='debts_lent')
    op.drop_table('debts_lent')
    # ### end Alembic commands ###
